name: Deploy Application

on:
  push:
    branch:
      - master

jobs:
  create-deployment-artifacts:
    name: create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: complile css and javascript
        run: |
          npm install
          npm run prod
